version: '3'
services:
  node:
    build: .
    container_name: meals_backend
    volumes:
      - ./backend:/home/backend
    ports:
      - "3010:3010"
    depends_on:
      - postgres
  postgres:
    container_name: meal-prep-db
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./backend/sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./backend/sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
      - ./backend/sql/indexes.sql:/docker-entrypoint-initdb.d/4.indexes.sql
