version: '3'
services:
  node:
    build: .
    container_name: meals_backend
    volumes:
      - ./backend:/home/backend
    ports:
      - "3010:3010"
    depends_on:
      - mongodb
    networks:
      - app-network  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app-network
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - app-network
    depends_on:
      - mongodb  
networks:
  app-network:
    driver: bridge